name: "build"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1

      - name: build
        run: yarn install && yarn electron || true

      - name: ls
        run: ls ./release

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: release
